/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "outline": "#7B8272",
              "on-primary": "#ffffff",
              "surface-bright": "#FAF8F5",
              "primary-fixed-dim": "#2A573A",
              "on-background": "#1A1A1A",
              "error-container": "#ffdad6",
              "primary": "#1C3A27",
              "on-secondary": "#ffffff",
              "on-tertiary-fixed-variant": "#524312",
              "background": "#FAF8F5",
              "tertiary-container": "#FAF3DD",
              "on-secondary-fixed": "#1A1A1A",
              "on-surface-variant": "#4E5346",
              "tertiary-fixed-dim": "#D4AF37",
              "on-error-container": "#93000a",
              "surface-tint": "#1C3A27",
              "on-tertiary-fixed": "#1A1A1A",
              "tertiary-fixed": "#FAF3DD",
              "inverse-surface": "#303030",
              "on-surface": "#1A1A1A",
              "surface-container-low": "#F5F3EE",
              "secondary": "#8B3C2A",
              "on-secondary-container": "#8B3C2A",
              "tertiary": "#D4AF37",
              "secondary-fixed": "#F2DDD9",
              "surface-container-lowest": "#ffffff",
              "on-tertiary-container": "#524312",
              "on-primary-fixed-variant": "#1C3A27",
              "inverse-primary": "#2A573A",
              "surface": "#ffffff",
              "surface-container-highest": "#E6E2DA",
              "on-error": "#ffffff",
              "secondary-container": "#F2DDD9",
              "inverse-on-surface": "#FAF8F5",
              "on-primary-container": "#1C3A27",
              "surface-dim": "#E6E2DA",
              "error": "#ba1a1a",
              "secondary-fixed-dim": "#A34F3C",
              "surface-variant": "#F5F3EE",
              "primary-container": "#E2ECD9",
              "surface-container": "#EBE9E4",
              "on-primary-fixed": "#1C3A27",
              "on-secondary-fixed-variant": "#8B3C2A",
              "surface-container-high": "#EBE9E4",
              "outline-variant": "#C8C9C4",
              "primary-fixed": "#E2ECD9",
              "on-tertiary": "#1A1A1A"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "margin-desktop": "64px",
              "container-max": "1280px",
              "shadow-offset": "6px",
              "border-width": "4px",
              "gutter": "24px",
              "margin-mobile": "16px"
      },
      "fontFamily": {
              "body-md": ["Hanken Grotesk"],
              "headline-lg": ["Anybody"],
              "display-lg": ["Anybody"],
              "headline-md": ["Anybody"],
              "body-lg": ["Hanken Grotesk"],
              "label-bold": ["Space Grotesk"],
              "headline-lg-mobile": ["Anybody"],
              "anybody": ["Anybody"]
      },
      "fontSize": {
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "500"}],
              "headline-lg": ["48px", {"lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
              "display-lg": ["72px", {"lineHeight": "72px", "letterSpacing": "-0.04em", "fontWeight": "900"}],
              "headline-md": ["32px", {"lineHeight": "36px", "fontWeight": "700"}],
              "body-lg": ["20px", {"lineHeight": "30px", "fontWeight": "500"}],
              "label-bold": ["14px", {"lineHeight": "16px", "fontWeight": "700"}],
              "headline-lg-mobile": ["32px", {"lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
}
